name: Deploy EC2 with Terraform and Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Initialize Terraform
      run: terraform -chdir=terraform init

    - name: Apply Terraform
      id: terraform
      run: terraform -chdir=terraform apply -auto-approve

    - name: Extract Public IP
      run: echo "PUBLIC_IP=$(terraform -chdir=terraform output -raw public_ip)" >> $GITHUB_ENV

    - name: Install Ansible
      uses: sudo apt update && sudo apt install -y ansible

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i ansible/inventory.ini ansible/playbook.yml \
          --extra-vars "ansible_host=$PUBLIC_IP"

